name: Build Excel Workbook

on:
  workflow_dispatch:
  push:
    branches: [costeo-pasteleria]
    paths:
      - 'costeo-pasteleria/*.csv'
      - 'scripts/build_excel.py'

jobs:
  build-excel:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run build script
        run: python scripts/build_excel.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add costeo-pasteleria/modelo-costeo.xlsx
          if ! git diff --cached --quiet; then
            git commit -m "Update modelo-costeo.xlsx"
            git push
          else
            echo "No changes to commit"
          fi