name: Build Excel Costing Model

on:
  push:
    branches:
      - costeo-pasteleria
    paths:
      - 'costeo-pasteleria/*.csv'
      - 'scripts/build_excel.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-excel:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate Excel model
      run: |
        python scripts/build_excel.py
    
    - name: Upload Excel artifact
      uses: actions/upload-artifact@v4
      with:
        name: modelo-costeo-excel
        path: costeo-pasteleria/modelo-costeo.xlsx
        retention-days: 30
    
    - name: Commit and push updated Excel file
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add costeo-pasteleria/modelo-costeo.xlsx
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update Excel costing model [skip ci]"
          git push
        fi